spring:
  data:
    mongodb:
      database: chat_service
      port: 27017
  application:
    name: "chat"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://13.127.132.74:8888"