spring:
  data:
    mongodb:
      uri: "mongodb+srv://aravind777:@77SudhaRajan@aravind777.qkdp20j.mongodb.net/?retryWrites=true&w=majority&appName=aravind777"
  application:
    name: "chat"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://13.127.132.74:8888"