spring:
  data:
    mongodb:
      uri: "mongodb+srv://aravind777:%4077SudhaRajan@aravind777.qkdp20j.mongodb.net/chat_service?retryWrites=true&w=majority&appName=aravind777"
  application:
    name: "chat"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://18.116.208.129:8888"